# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IBuEvutUMCgCqg7RUutd91L1OSs9zBr8
"""

# Author: Alexander Clarke
# Date Created: 12/12/2023
# Course: ITT103
# Purpose: Reserve seats on a bus for first class, business class, and economy class.

# Initialize seats array and variables
seats = [['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]
totalSeats = 9
reservedSeats = 0

# Display menu and read user input
print("Welcome to Bus Seat Reservation!")
print("1. First Class")
print("2. Business Class")
print("3. Economy Class")
print("4. Quit")


class_input = input("Enter your choice: ")

if class_input.lower() == 'q' or class_input.lower() == 'quit':
   print("Goodbye!")
   exit()

# Reserve seat based on user input
if class_input.lower() == 'f' or class_input.lower() == 'first class' :
  print ("FIRST CLASS selected")
 #  reserveSeat(seats, totalSeats, reservedSeats, 'firstClass')
elif class_input.lower() == 'b' or class_input.lower() == 'business class' :
  print ("BUSINESS SELECTED")
   #reserveSeat(seats, totalSeats, reservedSeats, 'businessClass')
elif class_input.lower() == 'e' or class_input.lower() == 'economy class' :
  print ("economy class selected")
   #reserveSeat(seats, totalSeats, reservedSeats, 'economyClass')
else:
     print("Invalid seat!")

# Prompt user for row number
row_input = input("Enter row number (1-3): ")
print ("You have selected row" + row_input)
rowNumber = int(row_input)

if rowNumber <= 0:
   print("Number must be positive or greater than zero!")

# Prompt user for seat type (window or aisle)
seatType_input = input("Enter seat type (W/A): ")
print ("You have selected seat" + seatType_input)
seatType = seatType_input.lower()

# Reserve seat and display messagereserveSeat(seats, totalSeats, reservedSeats, seatType)

# Print reservation information
print("Reservation Type:", class_input.lower())
print("Total number of seats:", totalSeats)
print("Total number of seats reserved:", reservedSeats)

def reserveSeat(seats, totalSeats, reservedSeats, classType):
   for row in seats:
       for seat in row:
           if seat == classType:
               seats[row.index(seat)][seat.index(seat)] = 'R'
               reservedSeats += 1
               print("Reserving seat: row", row.index(seat) + 1, "column", seat.index(seat) + 1)
               break
   if reservedSeats == totalSeats:
       print("No more available seats!")
       exit()
   else:
       return